# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fred}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Johnny Khai Nguyen"]
  s.date = %q{2010-08-12}
  s.description = %q{Ruby wrapper for the St. Louis Federal Reserve FRED API}
  s.email = %q{johnnyn@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "fred.gemspec",
     "generators/fred/USAGE",
     "generators/fred/fred_generator.rb",
     "init.rb",
     "install.rb",
     "lib/fred.rb",
     "lib/fred/client.rb",
     "pkg/fred-0.1.0.gem",
     "tasks/fred_tasks.rake",
     "test/fixtures/category.xml",
     "test/fixtures/release.xml",
     "test/fixtures/releases.xml",
     "test/fixtures/series.xml",
     "test/fixtures/source.xml",
     "test/fixtures/sources.xml",
     "test/fred_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/phuphighter/fred}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the St. Louis Federal Reserve FRED API}
  s.test_files = [
    "test/fred_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
  end
end

